### PR TITLE
Add get_package_share_path method

### PR DESCRIPTION
**Pull request by DLu**
Rather than all the ugliness of `os.path.join` I would much rather write simpler python in my launch files, so rather than
```
import os
from ament_index_python.packages import get_package_share_directory
...
bringup_dir = get_package_share_directory('testpkg')
urdf_path = os.path.join(bringup_dir, 'urdf', 'doggo.urdf')
```
you could just write
```
from ament_index_python.packages import get_package_share_path
...
urdf_path = get_package_share_path('testpkg') / 'urdf/doggo.urdf'

```

### CODE REVIEW

**Review by audrow — COMMENTED** [review]
This looks like a good addition to me. Can you write a test for the new function and make the linter happy?

**Comment by DLu** [comment]
@audrow Linter is happy and now there's a test.

**Review by audrow — APPROVED** [review]
Looks good to me, I'll run CI.

**Comment by audrow** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/14694/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/9446/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/12359/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/14838/)

**Comment by audrow** [comment]
Thanks for the PR @DLu!

**Pull request merged**
