### PR TITLE
Address clang-tidy warnings

### PR DESCRIPTION
**Pull request by piraka9011**
Change formatting and initialization of certain methods and variables to resolve clang-tidy warnings.

Signed-off-by: Anas Abou Allaban <allabana@amazon.com>

### CODE REVIEW

**Review by wjwwood — APPROVED** [review]

**Comment by wjwwood** [comment]
CI:

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/9333/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/5020/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/7639/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/9252/)
* Windows-container [Build Status](http://ci.ros2.org/job/ci_windows-container/125/)

**Comment by wjwwood** [comment]
`uncrustify` is failing.

**Comment by piraka9011** [comment]
Kicking off another round of CI:

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/9338/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/5023/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/7645/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/9258/)
* Windows-container [Build Status](http://ci.ros2.org/job/ci_windows-container/128/)

**Review by wjwwood — APPROVED** [review]

**Comment by wjwwood** [comment]
Thanks for fixing it up and re-running CI!

**Pull request merged**
